unstable_features = true
max_width = 100
#use_small_heuristics="Max"
#chain_width=50
#fn_call_width=60
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
